# Generated by Django 2.1.7 on 2019-03-14 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190314_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.SmallIntegerField(choices=[(1, '👍'), (-1, '👎')]),
        ),
    ]
